
###SEND REQUEST

POST http://127.0.0.1:25000/api/setdata
Content-Type: application/json

{
    "name" : "kty",
    "task" : "call",
    "id" : 1
}

###

GET http://127.0.0.1:25000/api/hello

###

GET http://127.0.0.1:25000/api/sqlserver/on

###